server:
  port: 7777
  servlet:
    context-path: /

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@  # 当前激活配置，默认dev
  datasource:
    dynamic:
      strict: true # 使用严格模式处理
  flyway:
    clean-disabled: true
    baseline-on-migrate: true
    placeholder-replacement: false # 取消占位符检测
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml
    - src/main/java/com/hccake/ballcat/codegen/database/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ballcat:
  openapi:
    info:
      title: BallCat-Codegen Docs
      description: BallCat 代码生成器文档
      version: ${project.version}
      terms-of-service: http://www.ballcat.cn/
      license:
        name: Powered By BallCat
        url: http://www.ballcat.cn/
      contact:
        name: Hccake
        email: chengbohua@foxmail.com
        url: https://github.com/Hccake
    servers:
      - url: /api # 设置调试的 server 前缀为 /api

springdoc:
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true

# 生产环境时不应在配置文件中显示配置，防止暴露配置信息
# 请使用环境变量，或启动项目时使用 --jasypt.encryptor.password=xxxx 进行传参
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
